_target_: utils.llm_client.openai.OpenAIClient

# Using Aliyun Bailian API
# see more models at https://bailian.console.aliyun.com/?tab=model
model: qwen3-235b-a22b
temperature: 1.0
api_key: ${oc.env:DASHSCOPE_API_KEY,null}
base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
